---
- hosts: localhost
  connection: local
  gather_facts: false

  roles:
    - vpc 
#    - web
  tasks:
    - debug:
        msg: "Browse to http://{{ ansible_host }}"

    - pause:
        prompt: "Check for availability before terminate"
