---
- hosts: localhost
  connection: local
  gather_facts: false

  roles:
    - vpc 

- hosts: aws_ec2
  gather_facts: false
  roles:
    - httpd

- hosts: tag_Name_vm1
  gather_facts: false
  tasks:
    - debug:
        msg: "Browse to http://{{ ansible_host }}"

- hosts: tag_Name_vm2
  gather_facts: false
  tasks:
    - debug:
        msg: "Browse to http://{{ ansible_host }}"

#    - pause:
#        prompt: "Check for availability before terminate"
