- name: Install ntpstat
  yum:
    name: ntpstat
    state: present
  
- name: Check if chrony is synchronized
  command: ntpstat
  command: ntpstat
  register: ntpstat_rc
  ignore_errors: true

- name: Copy chrony configuration
  copy:
   src: group_vars/files/chrony.conf
   dest: /etc/chrony.conf
   backup: yes
  when: ntpstat_rc.rc != 0

- name: Restart chrony service
  systemd:
   name: chronyd
   state: restarted
  when: ntpstat_rc.rc != 0
